version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-app
    networks:
      - kafka-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/.lego/certificates:/etc/nginx/ssl:ro
    networks:
      - kafka-network
    depends_on:
      - fastapi

networks:
  kafka-network:
    external: true
